### ISSUE TITLE
Grammar etc. review 

### ISSUE THREAD

**Issue by paragonie-scott** [jedisct1/dip#1]
Just reviewing word choice, grammar, etc. Some of this might actually be correct as-is:

-----

Line 32:
>  these information have proved to be useful for enterprise defense

Possibly: "this information has" might flow better.

------

Line 98:
> not being actively serving malicious content any more

Possibly: "no longer actively serving malicious content"

------

Line 462:
> source ip

I think IP needs to be capitalized here.

**Comment by jedisct1** [comment]
Thanks for your early feedback, Scott!

Fixing now.
